### ISSUE TITLE
Deployment failing - Error running SSM RunCommand DC1/2 - Scenario 1

### ISSUE THREAD

**Issue by suguiura-aws** [aws-quickstart/quickstart-microsoft-activedirectory#62] opened 2020-03-17 03:18 UTC
For some reason SSM RunCommand is failing on DC1/2, scenario 1.
Looked around in SSM, but couldn't figure out what's wrong. CFN reference to S3 is correct, and I successfully downloaded the template file from inside the instance.
install-ad-modules.ps1 is the one showing on the logs, but just because is the first one. I tried to manually run the SSM RunCommand on the other scripts (like LCM-Config.ps1), and it fails too.

I've created a new SSM Document to download the S3 file to the instance (aws:downloadcontent) and it works fine.

On CloudWatch I'm getting:
----------ERROR-------
AccessDenied: Access Denied
status code: 403, request id: XXXXXX, host id: XXXXXX

----------ERROR-------
./install-ad-modules.ps1 : The term './install-ad-modules.ps1' is not recognized as the name of a cmdlet, function,
script file, or operable rogram. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\ProgramData\Amazon\SSM\InstanceData\i-XXXXXX\document\orchestration\XXXXXX\runPowerShellScript\_script.ps1:4 char:2
+ ./install-ad-modules.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : ObjectNotFound: (./install-ad-modules.ps1:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
failed to run commands: exit status 255

**Comment by deki** [comment] 2020-04-09 15:07
Same issue while deploying scenario 3
@davmayd any idea?

**Comment by davmayd** [comment] 2020-04-09 15:19
@deki If you clone the repository and upload its contents to a custom S3 bucket it should work. It seems to be an issue with the new aws-quickstart-<region> buckets

**Comment by deki** [comment] 2020-04-09 17:49
Ok thanks. I can confirm that a custom S3 bucket works. The parameter `QSS3BucketName` needs to be set for that.

**Comment by davmayd** [comment] 2021-08-02 21:28
Fixed by https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/pull/114

**Closed by davmayd** 2021-08-02 21:28 UTC

**Comment by fortran01** [comment] 2022-09-16 21:19
I am still getting the following issue.

```
PS C:\Windows\system32> Read-S3Object -BucketName "aws-quickstart" -Key "quickstart-microsoft-activedirectory/scripts/Modules/Module-AD/Module-AD.psd1" -File "C:\AWSQuickstart\Module-AD\Module-AD.psd1" -Region "
us-east-1"
Read-S3Object : Access Denied
```
